services:
  - type: web
    name: declare-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: declare-db
          property: connectionString
      - key: CLIENT_URL
        sync: false

databases:
  - name: declare-db
    plan: free
